### ISSUE TITLE
scan mode always starts from the beginning while scanning a website multiple times.

### ISSUE THREAD

**Issue by s41n1k** [osmedeus/osmedeus-base#2]
Hi,

I scan a domain and stop it in the middle. When I re-scan that domain it starts all over the beginning. But the previous versions of osmedeus are scanned from the last stage. Can you fix this ?

Thank you

**Comment by j3ssie** [comment]
Please check the usage first at `osmedeus help -h` or `osmedeus scan help -h`.

You can use `--resume` flag when doing `osmedeus scan -t example.com`. It will ignore the modules that have already been scanned if the report file of that module exists. 
But it is also recommend to do the scan again since the result might be change from time to time depend on your target.

**Comment by s41n1k** [comment]
`--resume `fag does not work.
I use this CMD
`osmedeus scan -T domain.txt -R`

after interrupting, I use the same cmd but again it's started from the beginning.

**Comment by j3ssie** [comment]
It can only resume if the module has already been done before and the file in the **reports** section was created.
Check it more in here: https://docs.osmedeus.org/workflow/other-fields/#reports
